dist: trusty
sudo: false

language: node_js
node_js:
  - "10.9.0"

addons:
  chrome: stable,

cache:
  directories:
     - ./node_modules

install:
  - npm install

script:
  - npm run test ng-boosted -- --no-watch --no-progress --browsers=ChromeHeadless
  - npm run build:docs

before_deploy: "echo 'Deployement launched...'"
deploy:
  - provider: pages
    skip_cleanup: true
    script: npm run build:docs
    github_token: $GITHUB_TOKEN
    keep_history: true
    local_dir: dist/Orange-Boosted-Angular
    fqdn: ng-boosted.orange.com
    on:
      branch: refacto-structure
  - provider: npm
    script: npm run build:lib
    email: $NPM_EMAIL
    api_key: $NPM_TOKEN
    local_dir: dist/ng-boosted
    on:
      tag: true
      all_branches: true
after_deploy: "echo 'Deployement Done !'"