dist: trusty
sudo: false

language: node_js
node_js:
  - "10.9.0"

addons:
  chrome: stable,

cache:
  directories:
     - ./node_modules

install:
  - npm install

script:
  - npm run test ng-boosted -- --no-watch --no-progress --browsers=ChromeHeadless

after_success:
  - npm run build:docs
  - npm run build:lib

before_deploy:
  - "echo 'Deployement launched...'"
  - cd dist
deploy:
  - provider: pages
    skip_cleanup: true
    script: cd Orange-Boosted-Angular
    github_token: $GITHUB_TOKEN
    keep_history: true
    deployment: dist/Orange-Boosted-Angular
    fqdn: ng-boosted.orange.com
    on:
      branch: refacto-structure
  - provider: npm
    skip_cleanup: true
    script: cd ng-boosted
    email: $NPM_EMAIL
    api_key: $NPM_TOKEN
    deployment: dist/ng-boosted
    on:
      tags: true
      all_branches: true
after_deploy: "echo 'Deployement Done !'"