dist: trusty
sudo: false

language: node_js
node_js:
  - "14.18.1"

addons:
  chrome: stable,

cache:
  directories:
     - ./node_modules

install:
  - npm install

jobs:
  include:
    - stage: Lib test
      script:
        - npm run test:lib
    - stage: Npm Release
      node_js: "14.18.1"
      script:
        - echo "Deploying to NPM..."
        - npm run build:lib
        - cp ./README.md dist/ng-boosted
      before_deploy:
        - cd dist/ng-boosted
      after_deploy:
        - cd ../../
      deploy:
        provider: npm
        skip_cleanup: true
        email: $NPM_EMAIL
        api_key: $NPM_TOKEN
        on:
          tags: true
          all_branches: true
    - stage: Deploy to Production
      node_js: "14.18.1"
      script:
        - echo "Deploying to gh Pages ..."
        - npm run build:lib
        - npm run build:docs
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN
        keep_history: true
        local_dir: dist/Orange-Boosted-Angular
        fqdn: ng-boosted.orange.com
        on:
          branch: main
          tags: true
