dist: trusty
sudo: false

language: node_js
node_js:
  - "10.4.1"

addons:
  chrome: stable,

cache:
  directories:
     - ./node_modules

install:
  - npm install

script:
  - npm run test ng-boosted -- --no-watch --no-progress --browsers=ChromeHeadless
  - npm run build-prod

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: dist/Orange-Boosted-Angular
  fqdn: ng-boosted.orange.com
  target_branch: test-gh-pages
  on:
    branch: refacto-structure